FROM pytorch/pytorch:2.3.1-cpu
WORKDIR /code
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 9002
CMD ["uvicorn","expert_app:app","--host","0.0.0.0","--port","9002"]
